Repository react-materialize/react-materialize, pull requests merged in 2018-12, with the labels that each got.

#543 Adding Icon dependency to chip component
  src/Chip.js
  test/Chip.spec.js
  test/__snapshots__/Chip.spec.js.snap
Labels: ready-to-merge

#705 Add the possibility to pass other props to Container
  src/Container.js
Labels: ready-to-merge

#708 fix merge
  package-lock.json
  package.json
Labels: ready-to-merge

#632 3.0.0 Button.js
  docs/src/pages/ButtonsPage.js
  docs/src/pages/Samples.js
  examples/SmallButton.js
  examples/VerticalFAB.js
  src/Button.js
  src/constants.js
  test/Button.spec.js
  test/__snapshots__/Modal.spec.js.snap
Labels: 3.0.0

#654 3.0.0 select.js
  src/Select.js
  src/index.js
  stories/Select.stories.js
  test/Select.spec.js
Labels: 3.0.0

#725 3.0.0 switch
  src/Switch.js
  src/index.js
  stories/Switch.stories.js
  test/Switch.spec.js
  test/__snapshots__/Switch.spec.js.snap
Labels: 3.0.0

#723 Implement RadioGroup
  src/RadioGroup.js
  src/index.js
  stories/RadioGroup.stories.js
  test/RadioGroup.spec.js
  test/__snapshots__/RadioGroup.spec.js.snap
Labels: 3.0.0

#728 Add time/date pickers
  src/DatePicker.js
  src/TimePicker.js
  src/index.js
  stories/DatePicker.stories.js
  stories/TimePicker.stories.js
Labels: 3.0.0

#731 Remove tag component
  examples/Chips.js
  src/Tag.js
  src/index.js
  test/Tag.spec.js
  test/__snapshots__/Tag.spec.js.snap
Labels: 3.0.0, wip
